### ISSUE TITLE
ValueError when doing link prediction with methods 'CGTCG-S', 'CGCN-S' and 'EvolveGCN'.

### ISSUE THREAD

**Issue by YueeXiang** [jhljx/CTGCN#5]
Hi, I have learnt a lot from your codes. 
But when I run the link prediction task with 'python3 main.py --config=config/uci.json --task=embedding --method=CTGCN-S', I met the error:

`ValueError: Output size (199,) is not compatible with broadcast dimensions of inputs (1, 199).`

I also met the same error when trying the methods 'CGCN-S' and 'EvolveGCN'.

**Comment by jhljx** [comment]
Can you provide output log with more detail?

**Comment by YueeXiang** [comment]
Hi, the command is
`python3 main.py --config=config/uci.json --task=embedding --method=CTGCN-S`
 
and the output log is like
```
args: Namespace(config=['config/uci.json'], method='CTGCN-S', task='embedding')
{'base_path': './data/uci', 'origin_folder': '1.format', 'core_folder': 'CTGCN/ctgcn_cores', 'embed_folder': '2.embedding/CTGCN-S', 'model_folder': 'CTGCN/model', 'model_file': 'ctgcn-s', 'node_file': 'nodes_set/nodes.csv', 'file_sep': '\t', 'start_idx': 0, 'end_idx': -1, 'duration': 7, 'embed_dim': 128, 'use_cuda': True, 'thread_num': 30, 'epoch': 20, 'lr': 0.001, 'batch_size': 2048, 'load_model': False, 'shuffle': True, 'export': 'train_ratio': 0.5, 'val_ratio': 0.3, 'test_ratio': 0.2}

start_idx =  0 , end_idx =  7 , duration =  7

start CTGCN-S embedding!

idx =  0 , duration =  7

Traceback (most recent call last):
  File "main.py", line 129, in <module>
    main(sys.argv)
  File "main.py", line 108, in main
    embedding_task(args.method, param_dict)
  File "main.py", line 59, in embedding_task
    gnn_embedding(method, args)
  File "/home/usr/CTGCN-master/train.py", line 272, in gnn_embedding
    input_dim, adj_list, x_list, edge_list, node_dist_list = get_input_data(method, idx, time_length, data_loader, args)
  File "/home/usr/CTGCN-master/train.py", line 73, in get_input_data
    x_list, input_dim = data_loader.get_degree_feature_list(origin_base_path, start_idx=idx, duration=time_length, sep=file_sep, init_type=init_type, std=std)
  File "/home/usr/CTGCN-master/helper.py", line 143, in get_degree_feature_list
    fea_list.append(np.random.normal(degree, std, max_degree + 1))
  File "mtrand.pyx", line 1497, in numpy.random.mtrand.RandomState.normal
  File "_common.pyx", line 541, in numpy.random._common.cont
  File "_common.pyx", line 459, in numpy.random._common.cont_broadcast_2
  File "_common.pyx", line 229, in numpy.random._common.validate_output_shape
ValueError: Output size (199,) is not compatible with broadcast dimensions of inputs (1, 199).
```

**Comment by jhljx** [comment]
Well, it's a quite interesting bug. This bug is due to the numpy version. As I use the numpy==1.18.1, the degrees variable from line 121 of the `helper.py` file is a numpy array with shape (N, 1) where N is the node number. Then we need to iterate the degrees array in line 130 and the variable `degree` is a numpy array with shape (1, 1). In numpy 1.18.1 version, `numpy.random.normal` can receive the first variable with shape (1, 1). But I tested when using higher numpy version such as numpy==1.19.0, it will raise the Exception you have shown above. 

I think under your numpy version, you can use the following line to replace the line 121 of the `helper.py` file.

    degrees = spadj.sum(axis=1).A.flatten()

then the `degrees` variable will be a ndarray with shape (N, ). And in line 130, the variable `degree` will be a scalar.

**Comment by YueeXiang** [comment]
I try to replace Line 121 of `helper.py` by ```degrees = adj.sum(axis=1).A.flatten()``` but it still raises the same Exception as I have shown earlier. So I reinstall numpy==1.18.1 and it works! 
Thanks so much for your patient reply and wonderful codes! I really learn a lot from your repo.

**Comment by abubakhari** [comment]
thanks so much for the guidance @  jhljx and YueeXiang, i had also suffered the same problem, but by following this closed issue. I have succeeded in running the code

**Comment by MiladInk** [comment]
Hi All, thanks for the great explanation. Unfortunately, the hack does not work for me. When I update my numpy version to 1.18.1 and also the pandas and scipy so they can be supported by 1.18.1 but the code does not work then for me. The error is that:
```
Traceback (most recent call last):                                                                                                                                       
  File "main.py", line 129, in <module>                                                                                                                                  
    main(sys.argv)                                                                                                                                                       
  File "main.py", line 108, in main                                                                                                                                      
    embedding_task(args.method, param_dict)                                                                                                                              
  File "main.py", line 44, in embedding_task                                                                                                                             
    from train import gnn_embedding                                                                                                                                      
  File "/home/aghajohm/repos/CTCGN-sci4cast/train.py", line 8, in <module>                                                                                               
    from metrics import NegativeSamplingLoss, ReconstructionLoss, VAELoss, VAEClassificationLoss                                                                         
  File "/home/aghajohm/repos/CTCGN-sci4cast/metrics.py", line 9, in <module>                                                                                             
    from sklearn.preprocessing import label_binarize                                                                                                                     
  File "/home/aghajohm/repos/CTCGN-sci4cast/env/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>                                                   
    from .base import clone                                                                                                                                              
  File "/home/aghajohm/repos/CTCGN-sci4cast/env/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>                                                       
    from .utils import _IS_32BIT                                                                                                                                         
  File "/home/aghajohm/repos/CTCGN-sci4cast/env/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 22, in <module>                                             
    from .murmurhash import murmurhash3_32                                                                                                                               
  File "sklearn/utils/murmurhash.pyx", line 1, in init sklearn.utils.murmurhash                                                                                          
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject 
```
